//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarea_de_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class candidatos
    {
        public string cedula { get; set; }
        public string nombre { get; set; }
        public string partido { get; set; }
        public string plataforma { get; set; }
        public int edad { get; set; }
    
        public virtual partidos partidos { get; set; }
        public virtual plataformas plataformas { get; set; }
    }
}
