//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarea_de_MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eleccionesEntities : DbContext
    {
        public eleccionesEntities()
            : base("name=eleccionesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
            modelBuilder.Entity<candidatos>()
                .HasRequired(c => c.nombre);
        }
    
        public virtual DbSet<candidatos> candidatos { get; set; }
        public virtual DbSet<partidos> partidos { get; set; }
        public virtual DbSet<plataformas> plataformas { get; set; }
        public virtual DbSet<votos> votos { get; set; }
    }
}
