//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarea_de_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class plataformas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public plataformas()
        {
            this.candidatos = new HashSet<candidatos>();
        }
    
        public string plataforma_nombre { get; set; }
        public string partido { get; set; }
        public string posicion_espectro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<candidatos> candidatos { get; set; }
        public virtual partidos partidos { get; set; }
    }
}
